### ISSUE TITLE
Unable to resolve

### ISSUE THREAD

**Issue by codekiln** [jianli/git-get-merge#8]
This command is a great idea, but `git get-merge 3703b6c51e95c1649aac7426c826dbedd8ded7fa` or any other commit just returns "Unable to resolve" for me. Any tips?

**Comment by jianli** [comment]
What repository are you actually referring to?

**Comment by codekiln** [comment]
Sorry, it's a private repo. I just wondered if this had come up for other people.

**Comment by jianli** [comment]
The only thing I can think of is your repository might not have a `master` branch. But without being able to look at the repository it's impossible to debug.
